version: "3.9"

services:
    cache:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        networks:
            - hallway
        restart: unless-stopped

    worker:
        build: ./worker
        volumes:
            - ./worker/src:/app/src
        user: "1051:1051"
        ports:
            - "5000:5000"
        environment:
            - REDIS_URL=redis://cache:6379
            - PORT=5000
        networks:
            - hallway

networks:
    hallway:
        driver: bridge
