#!/usr/bin/env bash

set -e

main()
{
    case $1 in
        shell)
            bash
            ;;
        develop)
            printf "\t ..: Starting the developer loop\n"
            find ./ -name "*.py" | entr -r ./main.py
            ;;
        start)
            printf "\t ..: Starting queue worker\n"
            ./worker.py &
            printf "\t ..: Starting application\n"
            ./main.py
            ;;
        *)
            printf "\t ..: Invoking '$*'\n"
            exec "$@"
            ;;
    esac
}

cd /app/src
main "$@"
